/*
-- Query: 
-- Date: 2024-08-03 13:20
*/
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product01.jpg','Dumper toy','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',450.99);
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product02.jpg','Tractor toy','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',564.55);
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product03.jpg','Teddy dragon','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',60.95);
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product04.jpg','Summer clothing set','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',35.95);
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product05.jpg','Winter clothing set','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',29.99);
INSERT INTO `inventory` (`id`,`image`,`name`,`description`,`price`) VALUES (NULL,'product06.jpg','Octoberfast clothing set','Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit sint voluptate temporibus ad qui consequuntur voluptatem ducimus quis fugiat sequi et esse quidem eveniet culpa, consequatur, doloribus dignissimos quibusdam perspiciatis!',101.55);